(function(e){if("function"==typeof bootstrap)bootstrap("inquire",e);else if("object"==typeof exports)module.exports=e();else if("function"==typeof define&&define.amd)define(e);else if("undefined"!=typeof ses){if(!ses.ok())return;ses.makeInquire=e}else"undefined"!=typeof window?window.Inquire=e():global.Inquire=e()})(function(){var define,ses,bootstrap,module,exports;
return (function(e,t,n){function i(n,s){if(!t[n]){if(!e[n]){var o=typeof require=="function"&&require;if(!s&&o)return o(n,!0);if(r)return r(n,!0);throw new Error("Cannot find module '"+n+"'")}var u=t[n]={exports:{}};e[n][0].call(u.exports,function(t){var r=e[n][1][t];return i(r?r:t)},u,u.exports)}return t[n].exports}var r=typeof require=="function"&&require;for(var s=0;s<n.length;s++)i(n[s]);return i})({1:[function(require,module,exports){
var process=require("__browserify_process");/* parser generated by jison 0.4.10 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"expressions":3,"q":4,"group":5,"predicate":6,"binaryBool":7,"unaryBool":8,"(":9,")":10,"variable":11,"rel":12,"_var":13,"ALPHA":14,"DIGIT":15,"SAFE":16,"EXTRA":17,"ESCAPE":18,"NEQ":19,"GTE":20,"LTE":21,"EQ":22,"GT":23,"LT":24,"AND":25,"OR":26,"NOT":27,"ANDNOT":28,"$accept":0,"$end":1},
terminals_: {2:"error",9:"(",10:")",14:"ALPHA",15:"DIGIT",16:"SAFE",17:"EXTRA",18:"ESCAPE",19:"NEQ",20:"GTE",21:"LTE",22:"EQ",23:"GT",24:"LT",25:"AND",26:"OR",27:"NOT",28:"ANDNOT"},
productions_: [0,[3,1],[4,1],[4,1],[4,3],[4,3],[4,2],[5,3],[5,2],[6,3],[6,4],[11,3],[11,1],[11,2],[13,1],[13,1],[13,1],[13,1],[13,1],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[7,1],[7,1],[8,1],[8,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:return { "_parsedQueryString": $$[$0] };
break;
case 2:this.$ = $$[$0];
break;
case 3:this.$ = $$[$0];
break;
case 4:this.$ = { arity: "2", bool: $$[$0-1], left: $$[$0-2], right: $$[$0] };
break;
case 5:this.$ = { arity: "2", bool: $$[$0-1], left: $$[$0-2], right: $$[$0] };
break;
case 6:this.$ = { arity: "1", bool: $$[$0-1], value: $$[$0] };
break;
case 7:this.$ = { arity: "1", bool: "", value: $$[$0-1] };
break;
case 8:this.$ = { arity: "1", bool: "", value: ""};
break;
case 9:this.$ = { arity: "2", rel: $$[$0-1], left: $$[$0-2], right: $$[$0] };
break;
case 10:this.$ = { arity: "2", rel: $$[$0-2] + $$[$0-1], left: $$[$0-3], right: $$[$0] };
break;
case 11:this.$ = { arity: "1", bool: "", value: $$[$0-1] };
break;
case 12:this.$ = $$[$0];
break;
case 13:this.$ = $$[$0-1] + $$[$0];
break;
case 14:this.$ = yytext;
break;
case 15:this.$ = yytext;
break;
case 16:this.$ = yytext;
break;
case 17:this.$ = yytext;
break;
case 18:this.$ = yytext;
break;
case 19:this.$ = yytext;
break;
case 20:this.$ = yytext;
break;
case 21:this.$ = yytext;
break;
case 22:this.$ = yytext;
break;
case 23:this.$ = yytext;
break;
case 24:this.$ = yytext;
break;
case 25:this.$ = yytext;
break;
case 26:this.$ = yytext;
break;
case 27:this.$ = yytext;
break;
case 28:this.$ = yytext;
break;
}
},
table: [{3:1,4:2,5:3,6:4,8:5,9:[1,6],11:7,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15],27:[1,8],28:[1,9]},{1:[3]},{1:[2,1]},{1:[2,2],7:16,10:[2,2],25:[1,17],26:[1,18]},{1:[2,3],7:19,10:[2,3],25:[1,17],26:[1,18]},{4:20,5:3,6:4,8:5,9:[1,6],11:7,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15],27:[1,8],28:[1,9]},{4:21,5:3,6:4,8:5,9:[1,6],10:[1,22],11:23,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15],27:[1,8],28:[1,9]},{12:24,19:[1,25],20:[1,26],21:[1,27],22:[1,28],23:[1,29],24:[1,30]},{9:[2,27],14:[2,27],15:[2,27],16:[2,27],17:[2,27],18:[2,27],27:[2,27],28:[2,27]},{9:[2,28],14:[2,28],15:[2,28],16:[2,28],17:[2,28],18:[2,28],27:[2,28],28:[2,28]},{1:[2,12],9:[1,32],10:[2,12],11:31,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15],19:[2,12],20:[2,12],21:[2,12],22:[2,12],23:[2,12],24:[2,12],25:[2,12],26:[2,12]},{1:[2,14],9:[2,14],10:[2,14],14:[2,14],15:[2,14],16:[2,14],17:[2,14],18:[2,14],19:[2,14],20:[2,14],21:[2,14],22:[2,14],23:[2,14],24:[2,14],25:[2,14],26:[2,14]},{1:[2,15],9:[2,15],10:[2,15],14:[2,15],15:[2,15],16:[2,15],17:[2,15],18:[2,15],19:[2,15],20:[2,15],21:[2,15],22:[2,15],23:[2,15],24:[2,15],25:[2,15],26:[2,15]},{1:[2,16],9:[2,16],10:[2,16],14:[2,16],15:[2,16],16:[2,16],17:[2,16],18:[2,16],19:[2,16],20:[2,16],21:[2,16],22:[2,16],23:[2,16],24:[2,16],25:[2,16],26:[2,16]},{1:[2,17],9:[2,17],10:[2,17],14:[2,17],15:[2,17],16:[2,17],17:[2,17],18:[2,17],19:[2,17],20:[2,17],21:[2,17],22:[2,17],23:[2,17],24:[2,17],25:[2,17],26:[2,17]},{1:[2,18],9:[2,18],10:[2,18],14:[2,18],15:[2,18],16:[2,18],17:[2,18],18:[2,18],19:[2,18],20:[2,18],21:[2,18],22:[2,18],23:[2,18],24:[2,18],25:[2,18],26:[2,18]},{4:33,5:3,6:4,8:5,9:[1,6],11:7,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15],27:[1,8],28:[1,9]},{9:[2,25],14:[2,25],15:[2,25],16:[2,25],17:[2,25],18:[2,25],27:[2,25],28:[2,25]},{9:[2,26],14:[2,26],15:[2,26],16:[2,26],17:[2,26],18:[2,26],27:[2,26],28:[2,26]},{4:34,5:3,6:4,8:5,9:[1,6],11:7,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15],27:[1,8],28:[1,9]},{1:[2,6],10:[2,6]},{10:[1,35]},{1:[2,8],10:[2,8],25:[2,8],26:[2,8]},{10:[1,36],12:24,19:[1,25],20:[1,26],21:[1,27],22:[1,28],23:[1,29],24:[1,30]},{9:[1,32],11:37,12:38,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15],19:[1,25],20:[1,26],21:[1,27],22:[1,28],23:[1,29],24:[1,30]},{9:[2,19],14:[2,19],15:[2,19],16:[2,19],17:[2,19],18:[2,19],19:[2,19],20:[2,19],21:[2,19],22:[2,19],23:[2,19],24:[2,19]},{9:[2,20],14:[2,20],15:[2,20],16:[2,20],17:[2,20],18:[2,20],19:[2,20],20:[2,20],21:[2,20],22:[2,20],23:[2,20],24:[2,20]},{9:[2,21],14:[2,21],15:[2,21],16:[2,21],17:[2,21],18:[2,21],19:[2,21],20:[2,21],21:[2,21],22:[2,21],23:[2,21],24:[2,21]},{9:[2,22],14:[2,22],15:[2,22],16:[2,22],17:[2,22],18:[2,22],19:[2,22],20:[2,22],21:[2,22],22:[2,22],23:[2,22],24:[2,22]},{9:[2,23],14:[2,23],15:[2,23],16:[2,23],17:[2,23],18:[2,23],19:[2,23],20:[2,23],21:[2,23],22:[2,23],23:[2,23],24:[2,23]},{9:[2,24],14:[2,24],15:[2,24],16:[2,24],17:[2,24],18:[2,24],19:[2,24],20:[2,24],21:[2,24],22:[2,24],23:[2,24],24:[2,24]},{1:[2,13],10:[2,13],19:[2,13],20:[2,13],21:[2,13],22:[2,13],23:[2,13],24:[2,13],25:[2,13],26:[2,13]},{9:[1,32],11:39,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15]},{1:[2,4],10:[2,4]},{1:[2,5],10:[2,5]},{1:[2,7],10:[2,7],25:[2,7],26:[2,7]},{1:[2,11],10:[2,11],19:[2,11],20:[2,11],21:[2,11],22:[2,11],23:[2,11],24:[2,11],25:[2,11],26:[2,11]},{1:[2,9],10:[2,9],25:[2,9],26:[2,9]},{9:[1,32],11:40,13:10,14:[1,11],15:[1,12],16:[1,13],17:[1,14],18:[1,15]},{10:[1,36]},{1:[2,10],10:[2,10],25:[2,10],26:[2,10]}],
defaultActions: {2:[2,1]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    this.lexer.setInput(input);
    this.lexer.yy = this.yy;
    this.yy.lexer = this.lexer;
    this.yy.parser = this;
    if (typeof this.lexer.yylloc == 'undefined') {
        this.lexer.yylloc = {};
    }
    var yyloc = this.lexer.yylloc;
    lstack.push(yyloc);
    var ranges = this.lexer.options && this.lexer.options.ranges;
    if (typeof this.yy.parseError === 'function') {
        this.parseError = this.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    function lex() {
        var token;
        token = self.lexer.lex() || EOF;
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (this.lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + this.lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: this.lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: this.lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(this.lexer.yytext);
            lstack.push(this.lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = this.lexer.yyleng;
                yytext = this.lexer.yytext;
                yylineno = this.lexer.yylineno;
                yyloc = this.lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.call(yyval, yytext, yyleng, yylineno, this.yy, action[1], vstack, lstack);
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
undefined/* generated by jison-lex 0.2.1 */
var lexer = (function(){
var lexer = {

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input) {
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len - 1);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {

var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return "(";
break;
case 1:return ")";
break;
case 2:return "ALPHA";
break;
case 3:return "DIGIT";
break;
case 4:return "SAFE";
break;
case 5:return "EXTRA";
break;
case 6:return "ESCAPE";
break;
case 7:return "EQ";
break;
case 8:return "NEQ";
break;
case 9:return "GT";
break;
case 10:return "GTE";
break;
case 11:return "LT";
break;
case 12:return "LTE";
break;
case 13:return "AND";
break;
case 14:return "OR";
break;
case 15:return "NOT";
break;
case 16:return "ANDNOT";
break;
}
},
rules: [/^(?:\()/,/^(?:\))/,/^(?:[A-Za-z]+)/,/^(?:[0-9]+)/,/^(?:[\$\-_@\.\+]+)/,/^(?:[\*"\',]+)/,/^(?:%[A-Fa-f0-9]{2})/,/^(?:=)/,/^(?:!=)/,/^(?:>)/,/^(?:>=)/,/^(?:<)/,/^(?:<=)/,/^(?:&)/,/^(?:;)/,/^(?:!)/,/^(?:&!)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],"inclusive":true}}
};
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}
},{"__browserify_process":4,"fs":2,"path":3}],2:[function(require,module,exports){
// nothing to see here... no file methods for the browser

},{}],3:[function(require,module,exports){
var process=require("__browserify_process");function filter (xs, fn) {
    var res = [];
    for (var i = 0; i < xs.length; i++) {
        if (fn(xs[i], i, xs)) res.push(xs[i]);
    }
    return res;
}

// resolves . and .. elements in a path array with directory names there
// must be no slashes, empty elements, or device names (c:\) in the array
// (so also no leading and trailing slashes - it does not distinguish
// relative and absolute paths)
function normalizeArray(parts, allowAboveRoot) {
  // if the path tries to go above the root, `up` ends up > 0
  var up = 0;
  for (var i = parts.length; i >= 0; i--) {
    var last = parts[i];
    if (last == '.') {
      parts.splice(i, 1);
    } else if (last === '..') {
      parts.splice(i, 1);
      up++;
    } else if (up) {
      parts.splice(i, 1);
      up--;
    }
  }

  // if the path is allowed to go above the root, restore leading ..s
  if (allowAboveRoot) {
    for (; up--; up) {
      parts.unshift('..');
    }
  }

  return parts;
}

// Regex to split a filename into [*, dir, basename, ext]
// posix version
var splitPathRe = /^(.+\/(?!$)|\/)?((?:.+?)?(\.[^.]*)?)$/;

// path.resolve([from ...], to)
// posix version
exports.resolve = function() {
var resolvedPath = '',
    resolvedAbsolute = false;

for (var i = arguments.length; i >= -1 && !resolvedAbsolute; i--) {
  var path = (i >= 0)
      ? arguments[i]
      : process.cwd();

  // Skip empty and invalid entries
  if (typeof path !== 'string' || !path) {
    continue;
  }

  resolvedPath = path + '/' + resolvedPath;
  resolvedAbsolute = path.charAt(0) === '/';
}

// At this point the path should be resolved to a full absolute path, but
// handle relative paths to be safe (might happen when process.cwd() fails)

// Normalize the path
resolvedPath = normalizeArray(filter(resolvedPath.split('/'), function(p) {
    return !!p;
  }), !resolvedAbsolute).join('/');

  return ((resolvedAbsolute ? '/' : '') + resolvedPath) || '.';
};

// path.normalize(path)
// posix version
exports.normalize = function(path) {
var isAbsolute = path.charAt(0) === '/',
    trailingSlash = path.slice(-1) === '/';

// Normalize the path
path = normalizeArray(filter(path.split('/'), function(p) {
    return !!p;
  }), !isAbsolute).join('/');

  if (!path && !isAbsolute) {
    path = '.';
  }
  if (path && trailingSlash) {
    path += '/';
  }
  
  return (isAbsolute ? '/' : '') + path;
};


// posix version
exports.join = function() {
  var paths = Array.prototype.slice.call(arguments, 0);
  return exports.normalize(filter(paths, function(p, index) {
    return p && typeof p === 'string';
  }).join('/'));
};


exports.dirname = function(path) {
  var dir = splitPathRe.exec(path)[1] || '';
  var isWindows = false;
  if (!dir) {
    // No dirname
    return '.';
  } else if (dir.length === 1 ||
      (isWindows && dir.length <= 3 && dir.charAt(1) === ':')) {
    // It is just a slash or a drive letter with a slash
    return dir;
  } else {
    // It is a full dirname, strip trailing slash
    return dir.substring(0, dir.length - 1);
  }
};


exports.basename = function(path, ext) {
  var f = splitPathRe.exec(path)[2] || '';
  // TODO: make this comparison case-insensitive on windows?
  if (ext && f.substr(-1 * ext.length) === ext) {
    f = f.substr(0, f.length - ext.length);
  }
  return f;
};


exports.extname = function(path) {
  return splitPathRe.exec(path)[3] || '';
};

exports.relative = function(from, to) {
  from = exports.resolve(from).substr(1);
  to = exports.resolve(to).substr(1);

  function trim(arr) {
    var start = 0;
    for (; start < arr.length; start++) {
      if (arr[start] !== '') break;
    }

    var end = arr.length - 1;
    for (; end >= 0; end--) {
      if (arr[end] !== '') break;
    }

    if (start > end) return [];
    return arr.slice(start, end - start + 1);
  }

  var fromParts = trim(from.split('/'));
  var toParts = trim(to.split('/'));

  var length = Math.min(fromParts.length, toParts.length);
  var samePartsLength = length;
  for (var i = 0; i < length; i++) {
    if (fromParts[i] !== toParts[i]) {
      samePartsLength = i;
      break;
    }
  }

  var outputParts = [];
  for (var i = samePartsLength; i < fromParts.length; i++) {
    outputParts.push('..');
  }

  outputParts = outputParts.concat(toParts.slice(samePartsLength));

  return outputParts.join('/');
};

},{"__browserify_process":4}],4:[function(require,module,exports){
// shim for using process in browser

var process = module.exports = {};

process.nextTick = (function () {
    var canSetImmediate = typeof window !== 'undefined'
    && window.setImmediate;
    var canPost = typeof window !== 'undefined'
    && window.postMessage && window.addEventListener
    ;

    if (canSetImmediate) {
        return function (f) { return window.setImmediate(f) };
    }

    if (canPost) {
        var queue = [];
        window.addEventListener('message', function (ev) {
            if (ev.source === window && ev.data === 'process-tick') {
                ev.stopPropagation();
                if (queue.length > 0) {
                    var fn = queue.shift();
                    fn();
                }
            }
        }, true);

        return function nextTick(fn) {
            queue.push(fn);
            window.postMessage('process-tick', '*');
        };
    }

    return function nextTick(fn) {
        setTimeout(fn, 0);
    };
})();

process.title = 'browser';
process.browser = true;
process.env = {};
process.argv = [];

process.binding = function (name) {
    throw new Error('process.binding is not supported');
}

// TODO(shtylman)
process.cwd = function () { return '/' };
process.chdir = function (dir) {
    throw new Error('process.chdir is not supported');
};

},{}],5:[function(require,module,exports){
'use strict';
var parser, empty, arity, relation, Inquire, toString$ = {}.toString;
parser = require('../lib/parser.js');
empty = function(it){
  var _;
  for (_ in it) {
    return false;
  }
  return true;
};
arity = function(op){
  var ref$;
  switch (ref$ = [op], false) {
  case !(function(it){
    return in$(it, ['!'].concat(''));
  })(ref$[0]):
    return '1';
  case !(function(it){
      return it == '=' || it == '!=' || it == '>' || it == '>=' || it == '<' || it == '<=' || it == '&' || it == '&!' || it == ';' || it == 'concat';
    })(ref$[0]):
    return '2';
  }
};
relation = function(op){
  var ref$;
  switch (ref$ = [op], false) {
  case !(function(it){
    return it === '=';
  })(ref$[0]):
    return 'eq';
  case !(function(it){
      return it === '!=';
    })(ref$[0]):
    return 'neq';
  case !(function(it){
      return it === '>';
    })(ref$[0]):
    return 'gt';
  case !(function(it){
      return it === '>=';
    })(ref$[0]):
    return 'gte';
  case !(function(it){
      return it === '<';
    })(ref$[0]):
    return 'lt';
  case !(function(it){
      return it === '<=';
    })(ref$[0]):
    return 'lte';
  }
};
Inquire = (function(){
  Inquire.displayName = 'Inquire';
  var prototype = Inquire.prototype, constructor = Inquire;
  /*  Warning, this thing is chocked full of side effects.
      It's mad hard to reason about.
      Be careful...
  */
  prototype.inquiry = {};
  /*  Bound constructor allows us to call:
      LiveScript
      `Inquire!` rather than `new Inquire!`
  
      Javascript
      `Inquire()` rather than `new Inquire()`
  */;
  function Inquire(key, val, arg$){
    var ref$, bool, ref1$, rel, options, this$ = this instanceof ctor$ ? this : new ctor$;
    ref$ = arg$ != null
      ? arg$
      : {}, bool = (ref1$ = ref$.bool) != null ? ref1$ : '&', rel = (ref1$ = ref$.rel) != null ? ref1$ : '=';
    options = {
      bool: bool,
      rel: rel
    };
    this$._analyze(key, val, options);
    return this$;
  } function ctor$(){} ctor$.prototype = prototype;
  /*  Helper function to choose the correct string to create.
      `key` Determines the route to take depending on one of these types:
          `Inquire` -> Wrap it in parens and concat it to the previous inquire.
          `Array`   -> Join everything with the bool and concat to previous.
          `String`  -> Relate the key and val then concat to previous.
          `Object`  -> Relate each key/val, join with the bool and concat.
          Rest      -> For anything else, just throw it away.
      `val` Currently only used as the value for strings.
      `options` Additional information for constructing the inquire.
          `bool`    -> Boolean predicate to join with.
          `rel`     -> Relational operator to relate keys with values.
  
      Returns this Allows for chaining of inquire's.
  */
  prototype._analyze = function(key, val, arg$){
    var ref$, bool, ref1$, rel, options;
    ref$ = arg$ != null
      ? arg$
      : {}, bool = (ref1$ = ref$.bool) != null ? ref1$ : '&', rel = (ref1$ = ref$.rel) != null ? ref1$ : '=';
    options = {
      bool: bool,
      rel: rel
    };
    switch (ref$ = [key], false) {
    case !(function(it){
      return it instanceof Inquire;
    })(ref$[0]):
      this._handleInquire(key, options);
      break;
    case !compose$([
        (function(it){
          return it === 'Array';
        }), (function(it){
          return toString$.call(it).slice(8, -1);
        })
      ])(ref$[0]):
      this._handleArray(key, options);
      break;
    case !compose$([
        (function(it){
          return it === 'String';
        }), (function(it){
          return toString$.call(it).slice(8, -1);
        })
      ])(ref$[0]):
      this._handleString(key, val, options);
      break;
    case !compose$([
        (function(it){
          return it === 'Function';
        }), (function(it){
          return toString$.call(it).slice(8, -1);
        })
      ])(ref$[0]):
      this._handleFunction(key, options);
      break;
    case !compose$([
        (function(it){
          return it === 'Object';
        }), (function(it){
          return toString$.call(it).slice(8, -1);
        })
      ])(ref$[0]):
      this._handleObject(key, options);
    }
    this._prune(this.inquiry);
    return this;
  };
  prototype._binary = function(key, val, options){
    var ref$, rel, bool;
    if (empty(this.inquiry)) {
      this.inquiry = {
        arity: arity(options.rel),
        rel: options.rel,
        left: key,
        right: val
      };
      if ('1' === arity(options.bool)) {
        this._unary(this, options);
      }
    } else {
      ref$ = (function(){
        var ref$;
        switch (ref$ = [options.bool, options.rel], false) {
        case !('!' === ref$[0] && '!' === ref$[1]):
          return ['&!', '\'\''];
        case !(true && true):
          return [options.bool, options.rel];
        }
      }()), rel = ref$[0], bool = ref$[1];
      if (rel === options.bool) {
        this.inquiry = {
          arity: arity(options.bool),
          bool: options.bool,
          left: this.inquiry,
          right: Inquire()._analyze(key, val, {
            arity: arity(options.bool),
            bool: options.bool,
            rel: options.rel
          }).inquiry
        };
      } else {
        this.inquiry = {
          arity: arity(rel),
          bool: rel,
          left: this.inquiry,
          right: Inquire()._analyze(key, val, {
            arity: arity(bool),
            bool: bool,
            rel: options.rel
          }).inquiry
        };
      }
    }
  };
  prototype._unary = function(val, options){
    this.inquiry = {
      arity: arity(options.bool),
      bool: options.bool,
      value: val.inquiry
    };
  };
  prototype._handleArray = function(array, options){
    var inquire, boolean, i$, len$, item;
    inquire = Inquire();
    boolean = (function(){
      var ref$;
      switch (ref$ = [options.bool], false) {
      case ';' !== ref$[0]:
        return 'or';
      default:
        return 'and';
      }
    }());
    for (i$ = 0, len$ = array.length; i$ < len$; ++i$) {
      item = array[i$];
      inquire[boolean](item, null, options);
    }
    this._handleInquire(inquire, {
      bool: options.bool,
      rel: options.rel
    });
  };
  prototype._handleFunction = function(func, options){
    var inquire;
    inquire = constructor();
    inquire.inquiry = func;
    this._handleInquire(inquire, {
      bool: options.bool,
      rel: options.rel
    });
  };
  prototype._handleInquire = function(inquire, options){
    var bool;
    if (empty(this.inquiry)) {
      bool = options.bool === '!' ? options.bool : '';
      this._unary(inquire, {
        bool: bool
      });
    } else {
      this._binary(inquire, null, {
        bool: options.bool,
        rel: options.bool
      });
    }
  };
  prototype._handleObject = function(object, options){
    var inquire, rel, key, val;
    inquire = Inquire();
    if (object._parsedQueryString != null) {
      this._unary({
        inquiry: object._parsedQueryString
      }, options);
      return;
    }
    rel = relation(options.rel);
    for (key in object) {
      val = object[key];
      inquire[rel](key, val, options);
    }
    this._handleInquire(inquire, {
      bool: options.bool,
      rel: options.rel
    });
  };
  prototype._handleString = function(key, val, options){
    var ref$;
    switch (ref$ = [toString$.call(val).slice(8, -1)], false) {
    case !(function(it){
      return it == 'Boolean' || it == 'Number' || it == 'String';
    })(ref$[0]):
      this._binary(key, val, options);
      break;
    default:
      this.parse(key);
    }
  };
  prototype._prune = function(it){
    if (it.arity === '1' && it.value.arity === '1' && it.bool !== '!') {
      this.inquiry = it.value;
      if (it.bool) {
        this.inquiry.bool = it.bool;
      }
      this._prune(this.inquiry);
    }
    if (it.arity === '2' && it.right.arity === '1' && it.bool === '&!') {
      it.right = it.right.value;
      this.inquiry = it;
      this._prune(this.inquiry);
    }
  };
  /*  Relational operators.
  */
  prototype.eq = function(key, val){
    return this._analyze(key, val, {
      rel: '='
    });
  };
  prototype.neq = function(key, val){
    return this._analyze(key, val, {
      rel: '!='
    });
  };
  prototype.gt = function(key, val){
    return this._analyze(key, val, {
      rel: '>'
    });
  };
  prototype.gte = function(key, val){
    return this._analyze(key, val, {
      rel: '>='
    });
  };
  prototype.lt = function(key, val){
    return this._analyze(key, val, {
      rel: '<'
    });
  };
  prototype.lte = function(key, val){
    return this._analyze(key, val, {
      rel: '<='
    });
  };
  /*  Boolean predicates.
  */
  prototype.and = function(key, val){
    return this._analyze(key, val, {
      bool: '&'
    });
  };
  prototype.or = function(key, val){
    return this._analyze(key, val, {
      bool: ';'
    });
  };
  prototype.not = function(it){
    return this._analyze(it, null, {
      bool: '!'
    });
  };
  /*  Make our Inquire actually look like a query string.
  */
  prototype.generate = function(){
    return "?" + this._gen(this._unwrap(this.inquiry));
  };
  prototype._unwrap = function(I){
    if (I.bool === '') {
      return this._unwrap(I.value);
    } else {
      return I;
    }
  };
  prototype._gen = function(I){
    var ref$;
    if ((ref$ = toString$.call(I).slice(8, -1)) == 'Array' || ref$ == 'Boolean' || ref$ == 'Number' || ref$ == 'String') {
      return encodeURIComponent(I);
    } else if (toString$.call(I).slice(8, -1) === 'Function') {
      return encodeURIComponent(I());
    } else if (empty(I)) {
      return '';
    } else if (I.arity === '1') {
      switch (ref$ = [I.bool], false) {
      case !(function(it){
        return it === 'empty';
      })(ref$[0]):
        return '';
      default:
        return I.bool + "(" + this._gen(this._unwrap(I.value)) + ")";
      }
    } else if (I.arity === '2') {
      switch (ref$ = [I.rel, I.bool], false) {
      case !(function(it){
        return it != null;
      }(ref$[0]) && true):
        return this._gen(I.left) + "" + I.rel + this._gen(I.right);
      case !(true && (function(it){
          return it === '&!';
        })(ref$[1])):
        return this._gen(I.left) + "" + I.bool + "(" + this._gen(I.right) + ")";
      case !(true && (function(it){
          return it === 'concat';
        })(ref$[1])):
        return "(" + this._gen(I.left) + ")&(" + this._gen(I.right) + ")";
      case !(true && function(it){
          return it != null;
        }(ref$[1])):
        return this._gen(I.left) + "" + I.bool + this._gen(I.right);
      }
    }
  };
  prototype.toString = function(){
    return this._gen(this.inquiry);
  };
  /*  Read in a query string, and return an inquire.
  */
  prototype.parse = function(it){
    var parsed;
    parsed = parser.parse(it);
    return this._analyze(parsed, null, {
      bool: ''
    });
  };
  /*  Fantasy-land
  
      Everything in here should be pure, and not mutate other things.
      This is the only place where you can guarantee anything.
  */
  /*  Semigroup
  
      1.  `a.concat(b).concat(c)` is equivalent to `a.concat(b.concat(c))`
          (associativity)
  
      `concat` method
  
      A value which has a Semigroup must provide a `concat` method.
      The `concat` method takes one argument:
  
        s.concat(b)
  
      1.  `b` must be a value of the same Semigroup
  
          1.  If `b` is not the same semigroup, behaviour of `concat` is
              unspecified.
  
      2.  `concat` must return a value of the same Semigroup.
  */
  /* concat :: Inquire a -> Inquire a -> Inquire a */
  prototype.concat = function(I){
    var oldI, newI;
    oldI = import$({}, this.inquiry);
    newI = constructor();
    newI.inquiry = {
      arity: '2',
      bool: 'concat',
      left: oldI,
      right: I.inquiry
    };
    return newI;
  };
  /*  Monoid
  
      A value that implements the Monoid specification must also implement
      the Semigroup specficiation.
  
      1. `m.concat(m.empty())` is equivalent to `m` (right identity)
      2. `m.empty().concat(m)` is equivalent to `m` (left identity)
  
      `empty` method
  
      A value which has a Monoid must provide an `empty` method on itself or
      its `constructor` object. The `empty` method takes no arguments:
  
        m.empty()
        m.constructor.empty()
  
      1. `empty` must return a value of the same Monoid
  */
  /* empty :: Inquire a */
  prototype.empty = function(){
    var newI;
    newI = constructor();
    newI.inquiry = {
      arity: '1',
      bool: 'empty',
      value: ''
    };
    return newI;
  };
  /*  Functor
  
      1. `u.map(function(a) { return a; }))` is equivalent to `u` (identity)
      2. `u.map(function(x) { return f(g(x)); })` is equivalent to
         `u.map(g).map(f)` (composition)
  
      `map` method
  
      A value which has a Functor must provide a `map` method.
      The `map` method takes one argument:
  
        u.map(f)
  
      1. `f` must be a function,
  
        1. If `f` is not a function, the behaviour of `map` is unspecified.
        2. `f` can return any value.
  
      2. `map` must return a value of the same Functor
  */
  /* map :: Inquire a -> (a -> b) -> Inquire b */
  prototype.map = function(f){
    return constructor(f(this.toString()));
  };
  /*  Applicative
  
      A value that implements the Applicative specification must also
      implement the Functor specification.
  
      A value which satisfies the specification of a Applicative does not
      need to implement:
  
      * Functor's `map`
        derivable as `function(f) { return this.of(f).ap(this); })}`
  
      1. `a.of(function(a) { return a; }).ap(v)` is equivalent to `v` (identity)
      2. `a.of(function(f) {
            return function(g) {
              return function(x) {
                return f(g(x))
              };
            };
          }).ap(u).ap(v).ap(w)`
          is equivalent to `u.ap(v.ap(w))` (composition)
      3. `a.of(f).ap(a.of(x))` is equivalent to `a.of(f(x))` (homomorphism)
      4. `u.ap(a.of(y))` is equivalent to
         `a.of(function(f) { return f(y); }).ap(u)` (interchange)
  
      `ap` method
  
      A value which has an Applicative must provide an `ap` method. The `ap`
      method takes one argument:
  
          a.ap(b)
  
      1. `a` must be an Applicative of a function,
  
        1. If `a` does not represent a function, the behaviour of `ap` is
           unspecified.
  
      2. `b` must be an Applicative of any value
  
      3. `ap` must apply the function in Applicative `a` to the value in
         Applicative `b`
  
  */
  /* ap :: Inquire (a -> b) -> Inquire a -> Inquire b*/
  prototype.ap = function(I){
    if (toString$.call(I.inquiry.value).slice(8, -1) === 'Function') {
      return constructor(this.inquiry.value(I.inquiry.value));
    } else {
      return constructor(this.inquiry.value(I.toString()));
    }
  };
  /*
      `of` method
  
      A value which has an Applicative must provide an `of` method on itself
      or its `constructor` object. The `of` method takes one argument:
  
          a.of(b)
          a.constructor.of(b)
  
      1. `of` must provide a value of the same Applicative
  
          1. No parts of `b` should be checked
  */
  /* of :: a -> Inquire a */
  prototype.of = function(a){
    return constructor(a);
  };
  /*  Chain
  
      1. `m.chain(f).chain(g)` is equivalent to
         `m.chain(function(x) { return f(x).chain(g); })` (associativity)
  
      `chain` method
  
      A value which has a Chain must provide a `chain` method. The `chain`
      method takes one argument:
  
        m.chain(f)
  
      1. `f` must be a function which returns a value
  
          1. If `f` is not a function, the behaviour of `chain` is unspecified.
          2. `f` must return a value of the same Chain
  
      2. `chain` must return a value of the same Chain
  */
  /* chain :: Inquire a -> (a -> Inquire b) -> Inquire b */
  prototype.chain = function(f){
    return f(this);
  };
  /*  Monad
  
      A value that implements the Monad specification must also implement
      the Applicative and Chain specifications.
  
      A value which satisfies the specification of a Monad does not need to
      implement:
  
      * Applicative's `ap`
        derivable as `function(m) {
                        return this.chain(function(f) {
                          return m.map(f);
                        });
                      }`
      * Functor's `map`
        derivable as `function(f) {
                        var m = this;
                        return m.chain(function(a) {
                          return m.of(f(a));
                        });
                      }`
  
      1. `m.of(a).chain(f)` is equivalent to `f(a)` (left identity)
      2. `m.chain(m.of)` is equivalent to `m` (right identity)
  
  */;
  return Inquire;
}());
/*  Static methods.
    We can do stuff like:
    LiveScript

    `Inquire.gt \a, 10` along with `Inquire!.gt \a, 10`.

    Javascript

    `Inquire.gt('a', 10)` along with `Inquire().gt('a', 10)`.
*/
Inquire.eq = function(key, val){
  return Inquire().eq(key, val);
};
Inquire.neq = function(key, val){
  return Inquire().neq(key, val);
};
Inquire.gt = function(key, val){
  return Inquire().gt(key, val);
};
Inquire.gte = function(key, val){
  return Inquire().gte(key, val);
};
Inquire.lt = function(key, val){
  return Inquire().lt(key, val);
};
Inquire.lte = function(key, val){
  return Inquire().lte(key, val);
};
Inquire.and = function(key, val){
  return Inquire().and(key, val);
};
Inquire.or = function(key, val){
  return Inquire().or(key, val);
};
Inquire.not = function(it){
  return Inquire().not(it);
};
Inquire.parse = function(it){
  return Inquire().parse(it);
};
/*  Exporting inquire.  */
if ((typeof module != 'undefined' && module !== null) && module.exports) {
  module.exports = Inquire;
} else {
  this.Inquire = Inquire;
}
if (typeof define === 'function') {
  define('Inquire', [], function(){
    return Inquire;
  });
}
function in$(x, arr){
  var i = -1, l = arr.length >>> 0;
  while (++i < l) if (x === arr[i] && i in arr) return true;
  return false;
}
function compose$(fs){
  return function(){
    var i, args = arguments;
    for (i = fs.length; i > 0; --i) { args = [fs[i-1].apply(this, args)]; }
    return args[0];
  };
}
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}
},{"../lib/parser.js":1}]},{},[5])(5)
});
;