// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var flatten;
  module.exports.id = function(it){
    return it;
  };
  module.exports.con = function(a, b){
    return a;
  };
  module.exports.flipCon = function(b, a){
    return a;
  };
  module.exports.equivalent = function(a, b){
    return true;
  };
  if (!Array.of) {
    Array.prototype.of = function(){
      return Array.prototype.slice.call(arguments);
    };
  }
  if (!Array.ap) {
    flatten = function(it){
      return it.reduce(curry$(function(x$, y$){
        return x$.concat(y$);
      }));
    };
    Array.prototype.ap = function(a2){
      return flatten(this.map(function(f){
        return a2.map(function(a){
          return f(a);
        });
      }));
    };
  }
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
